NEW_REGION_FORMAT_VERSION = 1451

REGION_CHUNK_LENGTH = 32

class NBTTags:
    END_TAG = 0
    BYTE_TAG = 1
    SHORT_TAG = 2
    INT_TAG = 3
    LONG_TAG = 4
    FLOAT_TAG = 5
    DOUBLE_TAG = 6
    BYTE_ARRAY_TAG = 7
    STRING_TAG = 8
    LIST_TAG = 9
    COMPOUND_TAG = 10
    INT_ARRAY_TAG = 11
    LONG_ARRAY_TAG = 12

    END_LENGTH = None
    BYTE_LENGTH = 1
    SHORT_LENGTH = 2
    INT_LENGTH = 4
    LONG_LENGTH = 8
    FLOAT_LENGTH = 4
    DOUBLE_LENGTH = 8